### PR TITLE
Single node: use static private IP

### PR DESCRIPTION
**Pull request by zhengchang907**
## Change
Update private IP to be static after creation for HA/DR solution with ASR.

## Test
[Build PAYG single artifact ](https://github.com/zhengchang907/rhel-jboss-templates/actions/runs/4139941829)
[Validate payg offer](https://github.com/zhengchang907/rhel-jboss-templates/actions/runs/4132687855)

[Build BYOS single artifact](https://github.com/zhengchang907/rhel-jboss-templates/actions/runs/4139940921)
[Validate byos offer](https://github.com/zhengchang907/rhel-jboss-templates/actions/runs/4132686535)

Signed-off-by: Zheng Chang <zhengchang@microsoft.com>

### CODE REVIEW

**Comment by istraka** [comment]
@zhengchang907 I might got confused, but I believe we should use a public IP for standalone offerings: https://dev.azure.com/azure-redhat-projects/azure-redhat-projects/_workitems/edit/162 (IMO the title is wrong, see my comment). Am I right?

**Comment by zhengchang907** [comment]
> @zhengchang907 I might got confused, but I believe we should use a public IP for standalone offerings: https://dev.azure.com/azure-redhat-projects/azure-redhat-projects/_workitems/edit/162 (IMO the title is wrong, see my comment). Am I right?

Hi @istraka yes you are right:
1. These two user stories' titles are wrong, I corrected them.
2. We should have public IPs for standalone(single node) offers, however the user stories are not in this sprint.

**Comment by istraka** [comment]
@zhengchang907 so do we want static ip address for single nodes? Under what circumstances can a non-static private ip get changed?

**Review by edburns — APPROVED** [review]

**Comment by zhengchang907** [comment]
> @zhengchang907 so do we want static ip address for single nodes? Under what circumstances can a non-static private ip get changed?

Hi @istraka, that is a good question. To ease the Azure Site Recovery based HA/DR solution, we do need static private IPs for VMs.

For example, in single node offer we configure the `jboss.bind.address.private` to be the private IP address of the VM, see [here](https://github.com/zhengchang907/rhel-jboss-templates/blob/singlenodehadr/eap74-rhel8-payg/src/main/scripts/jbosseap-setup-redhat.sh#L121). And when failover happens, we'd like the VM provisioned in target region to retain the same IP address as we have in the source region, otherwise our host won't be able to start without manually changes on the configuration.

From documentation [Retain IP addresses during failover](https://learn.microsoft.com/en-us/azure/site-recovery/site-recovery-retain-ip-azure-vm-failover) we know that: for Azure VMs configured with static IP addresses, Site Recovery tries to provision the same IP address for the target VM, if it's not in use."

**Comment by istraka** [comment]
Yeah, thanks a lot! I was wondering if restarting a vm could result into such state - private ip gets changed. I haven't encountered that, but I haven't really experimented with a mid-large cluster. Maybe a 2 or 3 :)

**Comment by zhengchang907** [comment]
> Yeah, thanks a lot! I was wondering if restarting a vm could result into such state - private ip gets changed. I haven't encountered that, but I haven't really experimented with a mid-large cluster. Maybe a 2 or 3 :)

Hi @istraka, I think restarting VMs won't result in IP reallocation, according to [Private IP addresses allocation method](https://learn.microsoft.com/en-us/azure/virtual-network/ip-services/private-ip-addresses#allocation-method):

"Dynamic: Azure assigns the next available unassigned or unreserved IP address in the subnet's address range. For example, Azure assigns 10.0.0.10 to a new resource, if addresses 10.0.0.4-10.0.0.9 are already assigned to other resources.
Dynamic is the default allocation method. Once assigned, dynamic IP addresses are released if a network interface is:
* Deleted
* Reassigned to a different subnet within the same virtual network.
* The allocation method is changed to static, and a different IP address is specified.
By default, Azure assigns the previous dynamically assigned address as the static address when you change the allocation method from dynamic to static."

**Pull request merged**
